apiVersion: v1
kind: Deployment
metadata:
  name: nginxproxy
  labels:
    app: proxy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: proxy
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: nginxproxy-container
        image: eu.gcr.io/lbg-cloud-incubation/swells-nginx-lbg-demo:latest
        ports:
        - containerPort: 80

