kind: Namespace
apiVersion: v1
metadata:
  name: {{ns}}
  labels:
    name: {{ns}}
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxproxy
  namespace: {{ns}}
  labels:
    app: proxy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: proxy
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: nginxproxy-container
        image: eu.gcr.io/lbg-cloud-incubation/swells-nginx-lbg-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: nginxproxy
  namespace: {{ns}}
spec:
  type: LoadBalancer
  selector:
    app: proxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80




