apiVersion: v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python
spec:
  replicas: 10
  selector:
    matchLabels:
      app: python
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python-container
        image: eu.gcr.io/lbg-cloud-incubation/swells-flask-lbg-demo:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: ClusterIP
  selector:
    app: python
  ports:
  - protocol: TCP
    port: 8080
  
