apiVersion: v1
kind: Pod
metadata:
  name: python-app
  labels:
    app: python
spec:
  containers:
  - name: python-container
    image: zebra779/pythonAPI:latest
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: ClusterIP
  selector:
    app: python
  ports:
  - protocol: TCP
    port: 8080
  
